### ISSUE TITLE
Draft lost on connection timeout

### ISSUE THREAD

**Issue by adericbourg** [ippontech/tatami#678]
0. I'm logged in Tatami
0. I go for a walk
0. When I come back, I write a new message: the pop-in opens properly
0. I send it, the pop-in closes properly...
0. ... but nothing happens

The connection had timed out and my message has been lost. 

There should be something to prevent from writing (and losing!) a new message when user is no longer connected.

**Comment by JustinRisch** [comment]
Commit 4fba1f8eda9294db0e43b030fcad116dfa2960a9 fixes this issue by logging a user out from the front-end (ie: You receive an alert, and then are redirected to login page).
