### ISSUE TITLE
Links sent in emails do not resolve

### ISSUE THREAD

**Issue by rlheritier** [ippontech/tatami#849]
I was mentioned on tatami and received the related notification email. I click the link in the email. It does not resolve. The URL structure changed. 
Perhaps the fix is to change the email templates.

See below.

Dear rlheritier,

Someone mentioned you on Tatami:
@ggruel
@rlheritier cool just tested on android no major bugs

Better than #everwin

#Congrats 

You can see this status on Tatami:
https://app.tatamisoft.com/tatami/home/status/b6746a30-e465-11e4-9e04-fe54008898dc

Regards,
Ippon Technologies

**Comment by jchampemont** [comment]
Oups sorry @hegek87 didn't see you self-assigned this issue a little while ago :/

**Comment by jxerome** [comment]
+1
