### ISSUE TITLE
Profile picture: make it smaller and clickable to see a bigger version

### ISSUE THREAD

**Issue by rlheritier** [ippontech/tatami#858]
The profile picture is a bit big. Reduce it by 33% and make it clickable to see the original image or a bigger version, etc.

**Comment by rlheritier** [comment]
"@jrisch @rlheritier My opinion on this is that there's no point in seeing a large version of our *own* picture. However, it makes sense to display a large picture when we navigate to someone else's profile."
ok need to have a design conversation about this. Not urgent.

**Comment by JustinRisch** [comment]
I like the first option. The second comment (make yours smaller, others' larger) would annoy me greatly. Websites should have consistent layout throughout all of their pages.

**Comment by jnarron** [comment]
I shrunk the home sidebar image to 150x150. Also now if you click on it it will show the original 200x200. Click it again and it will shrink back.
