### ISSUE TITLE
Clicking on a profile link does not scroll back to the top of the page

### ISSUE THREAD

**Issue by ludochane** [ippontech/tatami#860]
When you are on your timeline, scroll to the bottom of the page and then click on someone's profile.
The profile page is correctly loaded but we are on the middle of the page.
I think we should be positioned on the top of the page.

Browser : Chrome (last version)
OS : MacOS

**Comment by jnarron** [comment]
I fixed this behavior on the havoc branch. The havoc branch will be merged to master again sometime next week.
