### ISSUE TITLE
Javascript concatenation

### ISSUE THREAD

**Issue by aseigneurin** [ippontech/tatami#863]
Many requests are made to load Javascript files. This makes it very long to load the page.

We should concatenate Javascript files to improve the loading process.

**Comment by jnarron** [comment]
We've recently switched to the minified versions of most libraries. The page loading should be faster after the next deployment.

**Comment by aseigneurin** [comment]
I think minified versions of the scripts won't be enough. The problem at the moment is really the number of requests, not the size of the files.

Are you using Grunt or a similar tool? You could use a plugin similar to https://github.com/gruntjs/grunt-contrib-concat

**Comment by jnarron** [comment]
Ah I see. We are not using Grunt at the moment. We will have to look into that soon.

**Comment by jnarron** [comment]
Related to #681

**Comment by JustinRisch** [comment]
we're now using grunt and down to ~20ish requests. Thanks for the suggestion!
