### ISSUE TITLE
Display unread tatam count in page title

### ISSUE THREAD

**Issue by jchampemont** [ippontech/tatami#869]
Tatami used to display unread tatam count in page title (`<title>`).

This allows firefox to make application tab "glow" (https://support.mozilla.org/fr/questions/810451)

Exemple: twitter app tab is glowing on the screenshot below.

![apptabglow](https://cloud.githubusercontent.com/assets/371876/7227749/5cbcddb0-e753-11e4-8bb5-1c1cb9fcf6c8.PNG)

**Comment by JustinRisch** [comment]
Implemented. Thank you for letting us know!
