### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by dmartinpro** [ippontech/tatami#883]
Be able to know which version is currently deployed. Could be something written somewhere on the page, like StackOverflow ("rev 2015.4.27.2530"), or a specific entry in the About menu.

**Comment by hegek87** [comment]
This will appear in the footer on the next release.

**Comment by dmartinpro** [comment]
There is no footer with the endless scrolling timeline.

**Comment by hegek87** [comment]
@dmartinpro that is a good point. I'm looking into a better way to implement this now. It will either end up being infinite scroll with some space reserved for the footer, or a button to fetch more posts.

**Comment by dmartinpro** [comment]
It could be put in the left column, right under the "Who to Follow" block, or in the About menu.

**Comment by hegek87** [comment]
I like the idea of putting it under the Who To Follow block. Kind of reminds me of what facebook has. I'll fix this soon

**Comment by hegek87** [comment]
The version and build information is underneath the who to follow block on the timeline, and it's in a footer elsewhere.
