### ISSUE TITLE
Marionette to Angular

### ISSUE THREAD

**Issue by hellsingblack** [ippontech/tatami#890]
Bonjour,

J'aimerai savoir quelle a été la réflection derrière le changement 360 de marionette vers angular ? 

Merci

**Comment by rlheritier** [comment]
Peut-etre un changement a 45 degrés plutot que 360 :)
Raisons du changement de BackboneJS a AngularJS:
1- plus facile de faire des changements. Le code BackboneJS etait difficile a evoluer.
2- plus facile de trouver des programmeurs qui peuvent et veulent participer (toute participation est la bienvenue)

**Comment by hellsingblack** [comment]
Salut @rlheritier,

J'aimerais bien faire partie du groupe de développeur si possible, je fais parti du projet de base et est fait la transition backbone vers marionette. Sa me plairait de revenir sur ce projet.

Bye

**Comment by rlheritier** [comment]
Okay je vais te connecter! Cool!

**Comment by bescott1** [comment]
Bonjour,

Pour contribuer à Tatami il faut simplement:

- Fork Tatami
- Coder vos changement
- Envoyer un pull request sur la branche github-pullrequest

Nous demandons que tous nouveau pull request vienne avec des unit test de la forme Jasmine. Si vous voulez un project specific, vous pouvais faire: https://github.com/ippontech/tatami/issues/883 <https://github.com/ippontech/tatami/issues/883>

Merci,

Benjamin Scott
Scrum Master
bscott@ipponusa.com
