### ISSUE TITLE
CSS seems slightly broken

### ISSUE THREAD

**Issue by aseigneurin** [ippontech/tatami#901]
Looks like some spacing was lost. See the attached screenshots.

![css2](https://cloud.githubusercontent.com/assets/4038960/7599303/1b8a36c0-f901-11e4-80aa-97b6061d4d45.png)
![css](https://cloud.githubusercontent.com/assets/4038960/7599304/1b8b3dae-f901-11e4-8800-423dbdd9e3b7.png)

**Comment by JustinRisch** [comment]
will be resolved in the next hotfix
