### ISSUE TITLE
Profile picture incorrectly displayed on the Timeline page

### ISSUE THREAD

**Issue by aseigneurin** [ippontech/tatami#903]
On the Timeline page, the profile picture looks truncated:

![timeline](https://cloud.githubusercontent.com/assets/4038960/7599361/a4ca0866-f901-11e4-876f-51ba74ef9093.png)

However, it looks ok on the profile page:

![profile](https://cloud.githubusercontent.com/assets/4038960/7599364/ad7d7592-f901-11e4-97c7-1c6185ca36df.png)

**Comment by JustinRisch** [comment]
Will be solved in the next hot-fix :+1:
