### ISSUE TITLE
WP 8.1: Unable to log in with Google Account

### ISSUE THREAD

**Issue by dmartinpro** [ippontech/tatami#918]
Regression (I'm sure it was working some time ago)

Windows Phone 8.1 / IE 11 (Mobile) : Nothing happens (no redirection at all to Google account selection page) when clicking on the login button for Google Account whereas it works (with an error since LDAP connection is currently broken) with the classical connection form.

**Comment by JustinRisch** [comment]
This is a graphical glitch that will be repaired in the next patch! Some
users have luck with tapping the top edge of the button. We apologize for
the inconvenience.
