### ISSUE TITLE
Trend viewing isn't working

### ISSUE THREAD

**Issue by MathieuAA** [ippontech/tatami#921]
When clicking on a Trend (followed or not), I'm not redirected to the trend timeline page. Instead, it seems to go to the login page, and then instantly go back to my main page.

Here's the flow (I just activated Firebug to be able to see this):
- GET <the_trend> (200)
- GET tag_timeline (200)
- GET http://www.app.tatamisoft.com/app/components/home/tag/TagHeaderView.min.html (404)
- GET profile (200)
- GET admin (200)
- ...

**Comment by hegek87** [comment]
This issue has been fixed, will work as intended in the next deployment.
