### ISSUE TITLE
HashTag view broken

### ISSUE THREAD

**Issue by ptemplier** [ippontech/tatami#927]
when trying to follow a hashtag link (http://app.tatamisoft.com/#/home/tag/Blog)
I see the login screen for a few milliseconds then I'm brought back to the timeline.

when inspecting the console i can see a 404 error : 
- GET http://app.tatamisoft.com/app/components/home/tag/TagHeaderView.min.html 404 (Not Found)

**Comment by hegek87** [comment]
This is fixed by b86259827ddda1214f99fb65267724aaeb6e3d05

The fix will be deployed within the next few days.
