### ISSUE TITLE
Upgrade Spring and Cassandra client to use JDK 8 code

### ISSUE THREAD

**Issue by lnorregaard** [ippontech/tatami#937]
To be able to switch to JDK 8 code there is a need to switch to Spring 4 and replace Hector with Astyanax
I have started investigating to change this on my Fork. 

What is your take on this?

**Comment by jdubois** [comment]
We should instead move to the Cassandra Java Driver from Datastax.
With Cassandra 3.0 all this is going to die anyway.

**Comment by lnorregaard** [comment]
Ok, I will examine how we can change to the Cassandra Java Driver.

The Spring 4 pull request I have already made. In the pom files the Astyanax is commented out. I will change that with the Cassandra Java driver.

**Comment by lnorregaard** [comment]
I'm now looking into Spring data to use as the repository manager. 
I have some difficulty with the old cassandra schemes. First I will try to use the Spring data to create tables and so on. And then there is a need to migrate the old schemes to the new scheme. I could change all domain tables to lowercase?

**Comment by jdubois** [comment]
I would not use Spring Data Cassandra: it is neither an official project
from Pivotal or from Datastax, and last time I tried it it lacked many of
the new Cassandra features.
The Cassandra Driver is perfectly fine for doing a project like Tatami,
that's the one I use in JHipster and for many clients.

On Fri, Nov 20, 2015 at 4:02 PM, lnorregaard <notifications@github.com>
wrote:

> I'm now looking into Spring data to use as the repository manager.
> I have some difficulty with the old cassandra schemes. First I will try to
> use the Spring data to create tables and so on. And then there is a need to
> migrate the old schemes to the new scheme. I could change all domain tables
> to lowercase?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ippontech/tatami/issues/937#issuecomment-158424901>.
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by lnorregaard** [comment]
Ok, I will look at JHipster how it creates the repository, and try to replicate that to the tatami project.

Do you have anything I need to be aware of

**Comment by jdubois** [comment]
No, you should be able to migrate from the old Hector-based directory to the new CQL Driver, but that might take some time to understand how to migrate everything.
You could have a look at how we use Cassandra in JHipster, here is a sample application made with the Cassandra back-end: https://github.com/jhipster/jhipster-sample-app-cassandra
As I coded both Tatami and JHipster, there are many things in common between both projects

**Comment by lnorregaard** [comment]
I have now made a huge rewrite of the code. Also added swagger to the project. Only accessible if you login with a known user. I have no idea if the pull request is too big. But the code is rewritten with JDK 8 streams and using datastax driver.

**Comment by jdubois** [comment]
@lnorregaard this looks like an incredible amount of work to do!!! We wanted to have people at Ippon USA working on this, we should join efforts and work together.
Can you contact me by email?

**Comment by lnorregaard** [comment]
@jdubois I have sent you an email. Hope it is the correct email. Please inform me if you got the email?
