### ISSUE TITLE
Error on mvn jetty:run command

### ISSUE THREAD

**Issue by romach** [ippontech/tatami#947]
When I try to run Jetty with command `mvn jetty:run` I get error:

> [ERROR] Failed to execute goal on project web: Could not resolve dependencies for project fr.ippon.tatami:web:war:4.0.5: The following artifacts could not be resolved: fr.ippon.tatami:services:jar:4.0.5, fr.ippon.tatami:services:jar:tests:4.0.5: Failure to find fr.ippon.tatami:services:jar:4.0.5 in http://oss.sonatype.org/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-releases has elapsed or updates are forced -> [Help 1]

Can somebody help to solve this problem?

**Comment by hegek87** [comment]
It's upset because the dependencies that web relies on (services) cannot be found. You need to build this first. From the root directory, run `mvn install` this will build all the dependencies, then you can do `cd web` and finally `mvn jetty:run`
