### ISSUE TITLE
Your project ippontech/tatami is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [ippontech/tatami#952]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  org.apache.httpcomponents httpclient (pom.xml)
  version: 4.2.2

  Jira issues:
  Flag issues in NTLM implementation prevent authentication on some servers
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1266?filter=allopenissues
  NTLM: Authenticating against some servers throws an exception
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1268?filter=allopenissues
  BrowserCompatSpec: cookies values containing spaces are forwarded without quotes
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1269?filter=allopenissues
  CachingHttpClient sends a 304 Not Modified to an unconditional request
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1277?filter=allopenissues
  NullPointerException (apparently) when authenticating
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1279?filter=allopenissues
  Use of toUpperCase() in NTLM engine may fail on non-US locales
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1283?filter=allopenissues
  HttpClient treats URI fragments in URIs inconsistently
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1286?filter=allopenissues
  The HttpGet() and likely other method objects should accept only absoluteURI with path specified 
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1291?filter=allopenissues
  proxy with kerberos auth is not woking
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1293?filter=allopenissues
  CircularRedirectException is falsely thrown on URI case mismatch
  affectsVersions:4.1.3;4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1294?filter=allopenissues
  Null pointer exception when using default host and virtual host with port -1
  affectsVersions:4.2.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1296?filter=allopenissues
  SSLSocketFactory.createSystemSSLContext causes java.security.UnrecoverableKeyException: Password verification failed
  affectsVersions:4.2.2;4.2.3;4.2.4;4.3 Alpha1;4.3 Beta1;4.3 Final
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1320?filter=allopenissues

  2  commons-io commons-io (pom.xml)
  version: 2.3

  Jira issues:
  What should happen in FileUtils.sizeOf[Directory] when an overflow takes place?
  affectsVersions:2.3
  https://issues.apache.org/jira/projects/IO/issues/IO-323?filter=allopenissues
  FileUtils.writeLines uses unbuffered IO
  affectsVersions:2.3
  https://issues.apache.org/jira/projects/IO/issues/IO-329?filter=allopenissues
  BOMInputStream wrongly detects UTF-32LE_BOM files as UTF-16LE_BOM files in method getBOM()
  affectsVersions:2.3
  https://issues.apache.org/jira/projects/IO/issues/IO-331?filter=allopenissues
  Commons IO Tailer does not respect UTF-8 Charset
  affectsVersions:2.3
  https://issues.apache.org/jira/projects/IO/issues/IO-354?filter=allopenissues
  IOUtils copyLarge() and skip() methods are performance hogs
  affectsVersions:2.3;2.4
  https://issues.apache.org/jira/projects/IO/issues/IO-355?filter=allopenissues
  Regression in FileUtils.readFileToString from 2.0.1
  affectsVersions:2.1;2.2;2.3;2.4
  https://issues.apache.org/jira/projects/IO/issues/IO-453?filter=allopenissues

  3  ch.qos.logback logback-classic (pom.xml)
  version: 1.0.13

  Jira issues:
  Prudent FileAppender is stopped if a thread is ever interrupted prior to a logging call
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-875?filter=allopenissues
  Deadlock in RollingFileAppender
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-891?filter=allopenissues
  SocketAppender causes Deadlock
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-896?filter=allopenissues
  SMTPAppender synchronization problem in Asynchronous mode
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-909?filter=allopenissues
  AsyncAppenderBase swallows InterruptedException
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-910?filter=allopenissues
  LoggerEvents are lost when sending over the SocketAppender
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-942?filter=allopenissues
  SyslogAppenderBase.stop() should check for non-null syslog output stream (sos) before calling close()
  affectsVersions:1.0.13
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-960?filter=allopenissues

  4  commons-lang commons-lang (pom.xml)
  version: 2.6

  Jira issues:
  Remove unnecessary synchronization from registry lookup in EqualsBuilder and HashCodeBuilder
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1230?filter=allopenissues
  LocaleUtils - DCL idiom is not thread-safe
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-803?filter=allopenissues
  Exception when combining custom and choice format in ExtendedMessageFormat
  affectsVersions:2.5;2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-917?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by jdubois** [comment]
Please don't spam us with automated stuff....
